---
general:
  botToken: ''
  guildId:
  listeningChannelId:
  allowedRole:
  fileDropClientFilePath:
  azureCredentialsJson:
servers:
- name:
  username:
  host:
scripts:
- name:
  type:
  command:
...