name: DeployDev

on:
  push:
    branches: [ "develop" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      run: docker build --platform linux/amd64 --tag evinrwatson/reso-bot:dev .

    - name: Docker Push
      run: docker push evinrwatson/reso-bot:dev
