name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: |
        docker build --tag evinrwatson/reso:latest .
        
    - name: Deploy to Docker Hub
      run: |
        docker push evinrwatson/reso:latest
